### ISSUE TITLE
疑似bug

### ISSUE THREAD

**Issue by LiangRongfu** [NLRX-WJC/Learn-Vue-Source-Code#10]
[变化侦测篇](https://nlrx-wjc.github.io/Learn-Vue-Source-Code/reactive/object.html#_2-%E4%BD%BFobject%E6%95%B0%E6%8D%AE%E5%8F%98%E5%BE%97%E2%80%9C%E5%8F%AF%E8%A7%82%E6%B5%8B%E2%80%9D)
Observer类中的walk调用defineReactive是否传少了个参数

**Comment by NLRX-WJC** [comment]
这里是没有问题的，walk中的defineReactive方法接收两个参数，第一个参数是一个对象obj，第二个参数是对象obj的键名，所以在walk中只传入了第一个参数obj，然后在walk方法中通过`Object.keys(obj)`得到第二个参数，最后将这两个参数传给defineReactive方法

**Comment by LiangRongfu** [comment]
源码是这样，但是这里不传第三参数，get的时候获取到的值是undefined吧？

**Comment by LiangRongfu** [comment]
看了源码有对只传两个参数的进行处理，这个问题是针对文中看到的代码提出，最好可以说明一下，哈哈哈

**Comment by NLRX-WJC** [comment]
嗯嗯，我明白你意思啦，你说的没错，我在写文档的时候，为了阅读起来便于理解，我在有些地方对源码做了些许改动，可能这块改的有点纰漏，你的理解是对的，我今天抽空修复一下哈，感谢提出宝贵意见，感谢感谢哈～
