### ISSUE TITLE
大佬，你好，我是个刚刚开始学前端的朋友，偶然，看到了你的文章，在下有问题前来请教。

### ISSUE THREAD

**Issue by mijaclan556** [NLRX-WJC/Learn-Vue-Source-Code#14]
怎么实现，像你这样页面部跳转，但可以正常的访问呢？
还有，我不是学习vue的。
[不转页看网页的效果.zip](https://github.com/NLRX-WJC/Learn-Vue-Source-Code/files/4015792/default.zip)

**Comment by NLRX-WJC** [comment]
你是说在页面内点击链接，局部跳转刷新吗？这个就是web应用的单页面应用（SPA），建议你了解下单页面应用

**Comment by mijaclan556** [comment]
好的谢谢------------------ 原始邮件 ------------------
发件人: "L!εsAμεr"<notifications@github.com>
发送时间: 2020年1月3日(星期五) 下午5:29
收件人: "NLRX-WJC/Learn-Vue-Source-Code"<Learn-Vue-Source-Code@noreply.github.com>;
抄送: "mijaclan556"<2734473891@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [NLRX-WJC/Learn-Vue-Source-Code] 大佬，你好，我是个刚刚开始学前端的朋友，偶然，看到了你的文章，在下有问题前来请教。 (#14)



你是说在页面内点击链接，局部跳转刷新吗？这个就是web应用的单页面应用（SPA），建议你了解下单页面应用
 
&mdash;
