### ISSUE TITLE
Observer

### ISSUE THREAD

**Issue by zyktrcn** [NLRX-WJC/Learn-Vue-Source-Code#15]
按照学习文档上的代码

`let car = new Observer({
  'brand':'BMW',
  'price':3000
})`

car是一个Observer对象
要访问car里的price属性需要通过value
即car.value.price

`let car = {
  'brand':'BMW',
  'price':3000
}`
`new Observer(car)`

如果是先声明对象
再用Observer去改写set和get才可以直接访问到price属性
即car.price

不知道是不是这样理解？

**Comment by NLRX-WJC** [comment]
是的，就是把原始对象`car`用`Observer`包装一下，为原始对象添加上拦截器，这样后续再读取这个原始对象时就可以侦听到该对象何时被读取、何时被修改了

> car是一个Observer对象
要访问car里的price属性需要通过value
即car.value.price

不用通过`car.value.price`访问，还是以`car.price`去访问，只是使用`Object.defineProperty`为对象添加了拦截器，访问方式不变。

**Comment by zyktrcn** [comment]
> 是的，就是把原始对象`car`用`Observer`包装一下，为原始对象添加上拦截器，这样后续再读取这个原始对象时就可以侦听到该对象何时被读取、何时被修改了
> 
> > car是一个Observer对象
> > 要访问car里的price属性需要通过value
> > 即car.value.price
> 
> 不用通过`car.value.price`访问，还是以`car.price`去访问，只是使用`Object.defineProperty`为对象添加了拦截器，访问方式不变。

我这边的测试代码用`let car = new Observer({...})`方式创建car对象，就需要用`car.value.price`的方式去访问price属性了。

**Comment by NLRX-WJC** [comment]
哦，我明白你意思了，确实是你说的这样，这是因为Observer类的构造函数里加了层`value`，我以为你说`Object.defineProperty`把对象改了呢，这块文档主要想表达的意思**利用Observer类可以把一个原始对象转化成响应式对象**哈
