### ISSUE TITLE
DOM-Diff算法时整个虚拟DOM的核心所在

### ISSUE THREAD

**Issue by Raywh** [NLRX-WJC/Learn-Vue-Source-Code#17]
应该是 DOM-Diff算法是整个虚拟DOM的核心所在
也许是太我小心眼了

**Comment by NLRX-WJC** [comment]
哈哈哈，感谢指正，感谢指正，已修改

**Comment by Raywh** [comment]
我这个，初学，请见谅 -o-

**Comment by Raywh** [comment]
请问大佬，学了一段时间了，感觉vue 还是无法下手 ，用过jQuery layui 的初学者。———— @NLRX-WJC
