### ISSUE TITLE
将模板编译篇放在虚拟DOM篇之前是否更合适？

### ISSUE THREAD

**Issue by LiPinghai** [NLRX-WJC/Learn-Vue-Source-Code#18]
逻辑顺序上更合理？

**Comment by NLRX-WJC** [comment]
首先，感谢提出的宝贵意见。
其实本该如你所将的这样，因为逻辑上是把模板编译完成了才有的虚拟DOM，但是如果把模板编译放在虚拟DOM之前介绍的话，在介绍模板编译原理中又会涉及到一些VNode相关的东西，而虚拟DOM里几乎没怎么涉及到模板编译，所以我在行文中干脆把虚拟DOM提前来介绍。
以上，是我的一点考虑。
