### ISSUE TITLE
 发现一处typo

### ISSUE THREAD

**Issue by smallbonelu** [NLRX-WJC/Learn-Vue-Source-Code#20]
[Vue的DOM Diff中更新节点的注释](https://nlrx-wjc.github.io/Learn-Vue-Source-Code/virtualDOM/patch.html#_5-%E6%9B%B4%E6%96%B0%E8%8A%82%E7%82%B9)
`
49 // 若有，vnode的text属性与oldVnode的text属性是否相同？
50  else if (oldVnode.text !== vnode.text) {
51    // 若相同：用vnode的text替换真实DOM的文本
52    nodeOps.setTextContent(elm, vnode.text)
53  }
`
上面51行是不是应该是“若不相同”？

**Comment by NLRX-WJC** [comment]
感谢指正，已修复
