### ISSUE TITLE
请问这是最新版2.6.11的源码解析吗？

### ISSUE THREAD

**Issue by wpnl** [NLRX-WJC/Learn-Vue-Source-Code#21]
为什么我clone下来的最新版的vue源码，里面wtacher类的update方法，计算属性的watcher是没有了getAndInvoke这个方法，也就是说计算属性没有了对比新旧的值。

请问文档里的源码解析是什么版本的呢？

**Comment by NLRX-WJC** [comment]
可以看下2.5.x版本的呢，因为文档里的各章节内容在写作的时候不是按照顺序写的，有的在很早之前就已经写好了，所以有的部分对应的源码会旧一点，虽然源码版本不同，但是其设计思路基本都是一样的，没有大的出入呢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: FwFeng <notifications@github.com&gt;
发送时间: 2020年1月23日 00:19
收件人: NLRX-WJC/Learn-Vue-Source-Code <Learn-Vue-Source-Code@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[NLRX-WJC/Learn-Vue-Source-Code] 请问这是最新版2.6.11的源码解析吗？ (#21)




为什么我clone下来的最新版的vue源码，里面wtacher类的update方法，计算属性的watcher是没有了getAndInvoke这个方法，也就是说计算属性没有了对比新旧的值。
 
请问文档里的源码解析是什么版本的呢？
