### ISSUE TITLE
2. 如何根据AST生成render函数这节的示例是不是错了

### ISSUE THREAD

**Issue by liangdiyuan** [NLRX-WJC/Learn-Vue-Source-Code#22]
原文的：_c('div',{attrs:{"id":"NLRX"}},[_c('p'),[_v("Hello "+_s(name))]])
我觉得是：_c('div',{attrs:{"id":"NLRX"}},[_c('p',null,[_v("Hello "+_s(name))])])

**Comment by NLRX-WJC** [comment]
感谢指正，确实是笔误，已修复，再次感谢
