### ISSUE TITLE
为什么说Array需要单独进行数据监测

### ISSUE THREAD

**Issue by collins999** [NLRX-WJC/Learn-Vue-Source-Code#27]
![image](https://user-images.githubusercontent.com/58177074/77450789-bb691b00-6e2e-11ea-82d1-2e7aa4812527.png)

**Comment by NLRX-WJC** [comment]
这个问题挺好的。对，你的例子没有错，Array本质上也是Object，我们甚至可以把一个Array看作是如下样子的Object(这样显然是不准确的，但是便于我们理解)：
```js
let arr = [1,2,3]

let arrObj = {
    "0":1,
    "1":2,
    "2":3
}
```
可以看到，如果把`arr`看成`arrObj`，那么我们就可以使用`Object.defineProperty`来监测`arr`的变化。另外我们还知道，`Object.defineProperty`监测`Object`型数据时是给对象的每个`key/value`添加上了`getter`和`setter`，这样，对于`Object`型数据我们通过`key`值取值或设置值时就可以被监测到。

同理，数组`arr`的索引值恰好就是`arrObj`的`key`值，所以我们通过数组的索引值来获取数组值和修改数组值时是可以用`Object.defineProperty`监测到的。**但是**，数组并不是只能由索引值来获取或改变值，更常用的是使用数组的方法如`push`,`shift`等来操作数组，当使用这些数组方法来操作数组时，`Object.defineProperty`就监测不到了，所以`Vue`对`Array`型数据单独设计了数据监测方式。
