### ISSUE TITLE
初始化cmputed属性

### ISSUE THREAD

**Issue by majunchang** [NLRX-WJC/Learn-Vue-Source-Code#28]
observer目录下的Wathcer.js中   文档展示的代码 和vue的github的源码 不太一致

比如update方法  this.computed之后的判断

**Comment by NLRX-WJC** [comment]
是不一样，你看的很仔细哦。
是这样子的，在源码中，是先调用` update `方法，然后在` update `方法中调用`run`方法，在`run`方法中调用了数据变化的更新回调函数，源码这么做是因为在` update `方法中还处理了一些比如异步批量更新的情况。
而在文档中为了简单明了起见，将` update `方法和`run`方法合二为一，因为这一章是介绍变化侦测的，所以我删去了一些处理其他情况的代码，为了让逻辑更清晰，主要是为了说明当数据变化时会调用回调函数进行视图更新。
如果你已经明白了这一流程，可以去源码里探究具体的实现哦。

**Comment by majunchang** [comment]
update () {
        if (this.computed) {
            if (this.dep.subs.length === 0) {
                this.dirty = true
            } else {
                this.getAndInvoke(() => {
                    this.dep.notify()
                })
            }
        }
    }

比如这一段代码哈  这样逻辑很清晰 computed之后 判断subs的长度 也就是有无订阅 然后调用getAndInvoke

但是在vue源码中 我翻到这个方法 发现
update () {
    /* istanbul ignore else */
    if (this.lazy) {
      this.dirty = true
    } else if (this.sync) {
      this.run()
    } else {
      queueWatcher(this)
    }
  }
它用lazy替代了computed   然后第一个if判断中你那个 直接将this.lazy  = true  
主要是这一段 看不懂  。。。  不明白为什么只有赋值  而没有后续处理了

**Comment by NLRX-WJC** [comment]
啊，我知道是什么情况了，源码中这块的逻辑有变化，在`2.5.17-beta0`版本是我文档里写的那样，而后来的版本就不是那样了，看来我得更新一下文档了，文档里面的有些篇章不是一次性都写好了，有的相隔时间有点久，导致跟源码版本有些出入，实在抱歉，我最近会抽空更新文档，你可以对着`2.5.17-beta0`版本先看。
我想源码改变了实现方式，但是我猜测设计思想应该没有变，还是通过比较新旧两个值来决定是否更新计算属性的值，这个也就是计算属性为什么会有缓存的原因。
接下来我会更新文档，实在抱歉。

**Comment by majunchang** [comment]
作者的文档写的已经很棒了&nbsp; 收益匪浅



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "难凉热血"<notifications@github.com&gt;; 
发送时间: 2020年3月31日(星期二) 下午5:12
收件人: "NLRX-WJC/Learn-Vue-Source-Code"<Learn-Vue-Source-Code@noreply.github.com&gt;; 
抄送: "流氓流年流浪"<2471978285@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [NLRX-WJC/Learn-Vue-Source-Code] 初始化cmputed属性 (#28)





 
啊，我知道是什么情况了，源码中这块的逻辑有变化，在2.5.17-beta0版本是我文档里写的那样，而后来的版本就不是那样了，看来我得更新一下文档了，文档里面的有些篇章不是一次性都写好了，有的相隔时间有点久，导致跟源码版本有些出入，实在抱歉，我最近会抽空更新文档，你可以对着2.5.17-beta0版本先看。
 
我想源码改变了实现方式，但是我猜测设计思想应该没有变，还是通过比较新旧两个值来决定是否更新计算属性的值，这个也就是计算属性为什么会有缓存的原因。
 
接下来我会更新文档，实在抱歉。
