### ISSUE TITLE
大佬，文档可否增加一键复制

### ISSUE THREAD

**Issue by Zhan-My** [NLRX-WJC/Learn-Vue-Source-Code#7]
As the title says

**Comment by NLRX-WJC** [comment]
复制？复制什么？文档中的代码还是文字？

**Comment by NLRX-WJC** [comment]
> As the title says

复制？复制什么？文档中的代码还是文字？

**Comment by NLRX-WJC** [comment]
如果需要转载或引用的话麻烦注明一下出处哈，尊重作者的辛苦付出，感谢感谢哈～～

**Comment by Zhan-My** [comment]
首先感谢作者提供的文档！我是说代码的一键复制；
第二个问题，我是纯学习，如有需要，肯定会注明出处，此乃江湖规矩

**Comment by NLRX-WJC** [comment]
好的，我回头研究一下这个文档工具，应该会有这个功能，可能是我没开启，感谢您的支持！！！
