### ISSUE TITLE
文档问题有点多哟，不过还是感谢

### ISSUE THREAD

**Issue by forever-z-133** [NLRX-WJC/Learn-Vue-Source-Code#8]
https://nlrx-wjc.github.io/Learn-Vue-Source-Code/reactive/object.html#_4-%E4%BE%9D%E8%B5%96%E5%88%B0%E5%BA%95%E6%98%AF%E8%B0%81

正则 `/[^\w.$]/` 其实搞不了 `'style.padding-top'` 这种带 `-` 的，感觉可以不加这个判断。

----

https://nlrx-wjc.github.io/Learn-Vue-Source-Code/reactive/object.html#_3-%E4%BE%9D%E8%B5%96%E6%94%B6%E9%9B%86

`depend` 时应该是 `this.addSub`；
`defineReactive` 里应该是 `Observer`。

----

https://nlrx-wjc.github.io/Learn-Vue-Source-Code/reactive/object.html#_4-%E4%BE%9D%E8%B5%96%E5%88%B0%E5%BA%95%E6%98%AF%E8%B0%81

Watcher 后面推荐加上实践代码，可以更方便运用。
```
new Watcher(car, 'price', (newValue, oldValue) => {
  console.log(newValue, oldValue);
});
car.price= 50;
```

**Comment by NLRX-WJC** [comment]
首先感谢您的指正，文档成文确实有点匆忙，不足之处在所难免，关于您提出的三个问题我回答如下：
1.这个正则主要是用来判断传入的字符串是否是一个形如“a.b”的取值路径字符串，如果是的话就会进入下面的根据路径解析，从而取值。
2.这两处确实是笔误。感谢指正，我会及时修改。
3.这里您提出的意见非常好，我会及时添加进去。

再次感谢您的指正！！
